/**
 * Deployed Supabase Edge function slugs: `supabase/functions/<slug>/index.ts` →
 * `GET|POST ${SUPABASE_URL}/functions/v1/<slug>`.
 *
 * Slugs are **verb-first** (CRUD / HTTP-style): e.g. `create-tracking-request`, `get-shipment`,
 * `create-customer-invite`. Group keys (`tracking`, `shipments`, …) are **caller grouping only**
 * (flat slug namespace).
 */
export const EDGE_FUNCTION_SLUGS = {
  tracking: {
    createRequest: "create-tracking-request",
    getContainerDetails: "get-container-details",
    searchContainers: "search-containers",
    syncContainer: "sync-container",
    syncStaleRequests: "sync-stale-tracking-requests",
    lookupBolContainers: "lookup-bol-containers",
    workspaceSummary: "get-workspace-summary",
    dashboardAnalytics: "get-tracking-dashboard-analytics",
    listRecentRequests: "list-recent-tracking-requests",
    listOperatorRequests: "list-operator-tracking-requests",
  },
  shipments: {
    get: "get-shipment",
    create: "create-shipment",
    update: "update-shipment",
    updateRisk: "update-shipment-risk",
    delete: "delete-shipment",
    reviewDocument: "review-shipment-document",
    claimAccess: "claim-shipment-access",
    postCustomerMessage: "post-customer-shipment-message",
    previewCustomer: "preview-customer-shipment",
    accessTab: "get-shipment-access-tab",
    updateAssignee: "update-shipment-assignee",
    updateTags: "update-shipment-tags",
    updateRootCause: "update-shipment-root-cause",
    updateNotificationSubscription: "update-shipment-notification-subscription",
    insertParticipant: "insert-shipment-participant",
    deleteParticipant: "delete-shipment-participant",
    revokeCustomerInvite: "revoke-customer-invite",
    revokeCustomerAccess: "revoke-shipment-customer-access",
    updateCustomerAccessSettings: "update-shipment-customer-access-settings",
    workspaceRow: "get-shipment-workspace-row",
    pickRows: "list-shipment-pick-rows",
  },
  customers: {
    createInvite: "create-customer-invite",
    acceptInvite: "accept-customer-invite",
    completeShipmentSetup: "complete-customer-shipment-setup",
    checkPortalAccessEmail: "check-portal-access-email",
    resolveAccessRequest: "resolve-customer-access-request",
    previewInvite: "preview-customer-invite",
  },
  reports: {
    getPublic: "get-public-report",
    postMessage: "post-report-message",
  },
  performance: {
    sendStaleReminders: "send-stale-shipment-reminders",
  },
  feedback: {
    submit: "submit-feedback",
    listAdmin: "list-admin-feedback",
    updateAdmin: "update-admin-feedback",
  },
  alerts: {
    list: "list-alerts",
    acknowledge: "acknowledge-alert",
    acknowledgeAll: "acknowledge-all-alerts",
  },
  shipmentsList: {
    operatorOverview: "list-operator-shipments",
    documentQueue: "list-document-queue",
    importerGranted: "list-importer-granted-shipments",
  },
  dashboard: {
    trackingSnapshot: "get-tracking-dashboard",
  },
  workspace: {
    createSignedUrl: "create-workspace-signed-url",
    getContainer: "get-container-workspace",
    getQuickSearch: "get-workspace-quick-search",
    postContainerMessage: "post-container-message",
    uploadContainerDocuments: "upload-container-documents",
    patchReportMessage: "patch-report-message",
    deleteReportMessage: "delete-report-message",
    patchAttachment: "patch-workspace-attachment",
    deleteAttachment: "delete-workspace-attachment",
    getShipmentScopeThread: "get-shipment-scope-thread",
    postShipmentMessage: "post-shipment-message",
    uploadShipmentDocuments: "upload-shipment-documents",
    listOrgShipmentMessageThreads: "list-org-shipment-message-threads",
    markShipmentThreadRead: "mark-shipment-thread-read",
    listImporterShipmentMessageThreads: "list-importer-shipment-message-threads",
    markImporterShipmentThreadRead: "mark-importer-shipment-thread-read",
    notifyBolImport: "notify-bol-import",
  },
  auth: {
    notifyPasswordChanged: "notify-password-changed",
  },
  profile: {
    getMy: "get-my-profile",
    updateMy: "update-my-profile",
    uploadImage: "upload-profile-image",
    deleteImage: "delete-profile-image",
    displayNames: "get-profile-display-names",
    updateRole: "update-profile-role",
  },
  onboarding: {
    status: "get-onboarding-status",
    completeOrganization: "complete-onboarding-organization",
  },
  tenantInvites: {
    list: "list-tenant-invites",
    create: "create-tenant-invite",
  },
  organizations: {
    listMemberships: "list-org-memberships",
    metrics: "get-org-metrics",
    members: "list-org-members",
    updateSettings: "update-org-settings",
    performanceSettingsGet: "get-org-performance-settings",
    performanceSettingsUpdate: "update-org-performance-settings",
    pendingAccessRequests: "list-pending-access-requests",
    customerDirectory: "get-customer-directory",
    imageGet: "get-org-image",
    imageUpload: "upload-org-image",
    imageDelete: "delete-org-image",
    create: "create-organization",
    inviteMember: "invite-organization-member",
    patchMember: "patch-organization-member",
    deleteMember: "delete-organization-member",
    adminMemberDirectory: "list-admin-org-member-directory",
  },
} as const;
