import {
  DASHBOARD_LOADING_CLASS,
  DASHBOARD_PANEL_BODY_CLASS,
  DASHBOARD_PANEL_CLASS,
  DASHBOARD_SECTION_DESC_CLASS,
  DASHBOARD_SECTION_TITLE_CLASS,
} from "../../constants";
import {
  CHART_AXIS_TICK,
  CHART_GRID_STROKE,
  CHART_PRIMARY_ORANGE,
  DASHBOARD_CHART_HEIGHT_CLASS,
} from "../DashboardCharts/constants";

export {
  DASHBOARD_PANEL_CLASS as DASHBOARD_TIME_TO_RESOLVE_PANEL_CLASS,
  DASHBOARD_PANEL_BODY_CLASS as DASHBOARD_TIME_TO_RESOLVE_PANEL_BODY_CLASS,
  DASHBOARD_SECTION_TITLE_CLASS as DASHBOARD_TIME_TO_RESOLVE_TITLE_CLASS,
  DASHBOARD_SECTION_DESC_CLASS as DASHBOARD_TIME_TO_RESOLVE_SUBTITLE_CLASS,
  DASHBOARD_LOADING_CLASS as DASHBOARD_TIME_TO_RESOLVE_LOADING_CLASS,
  DASHBOARD_CHART_HEIGHT_CLASS as DASHBOARD_TIME_TO_RESOLVE_CHART_HEIGHT_CLASS,
  CHART_PRIMARY_ORANGE,
  CHART_GRID_STROKE,
  CHART_AXIS_TICK,
};

export const CHART_REPLY_BLUE = "#0ea5e9";

export const DASHBOARD_TIME_TO_RESOLVE_LEGEND_CLASS =
  "mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-zinc-500 dark:text-zinc-400";

export const DASHBOARD_TIME_TO_RESOLVE_LEGEND_SWATCH_CLASS = "mr-1.5 inline-block h-2 w-2 rounded-full";
