import {
  DASHBOARD_LOADING_CLASS,
  DASHBOARD_PANEL_BODY_CLASS,
  DASHBOARD_PANEL_CLASS,
  DASHBOARD_SECTION_DESC_CLASS,
  DASHBOARD_SECTION_TITLE_CLASS,
} from "../../constants";

export {
  DASHBOARD_PANEL_CLASS as DASHBOARD_CHART_PANEL_CLASS,
  DASHBOARD_PANEL_BODY_CLASS as DASHBOARD_CHART_PANEL_BODY_CLASS,
  DASHBOARD_SECTION_TITLE_CLASS as DASHBOARD_CHART_TITLE_CLASS,
  DASHBOARD_SECTION_DESC_CLASS as DASHBOARD_CHART_SUBTITLE_CLASS,
  DASHBOARD_LOADING_CLASS as DASHBOARD_CHART_LOADING_CLASS,
};

export const DASHBOARD_CHARTS_GRID_CLASS = "grid gap-6 lg:grid-cols-2";

export const DASHBOARD_CHART_HEIGHT_CLASS = "mt-5 h-48 w-full";

export const CHART_PRIMARY_ORANGE = "#FF4E00";

export const CHART_GRID_STROKE = "rgba(161, 161, 170, 0.2)";

export const CHART_AXIS_TICK = "#a1a1aa";

export const CHART_BAR_COLORS = [
  CHART_PRIMARY_ORANGE,
  "#a1a1aa",
  "#d4d4d8",
  "#71717a",
  "#52525b",
  "#3f3f46",
] as const;
