import {
  DASHBOARD_EYEBROW_CLASS,
  DASHBOARD_LINK_CLASS,
  DASHBOARD_LOADING_CLASS,
  DASHBOARD_PANEL_BODY_CLASS,
  DASHBOARD_PANEL_CLASS,
  DASHBOARD_SECTION_DESC_CLASS,
  DASHBOARD_SECTION_TITLE_CLASS,
} from "../../constants";

export {
  DASHBOARD_PANEL_CLASS as DASHBOARD_BREAKDOWN_CARD_PANEL_CLASS,
  DASHBOARD_PANEL_BODY_CLASS as DASHBOARD_BREAKDOWN_CARD_PANEL_BODY_CLASS,
  DASHBOARD_SECTION_TITLE_CLASS as DASHBOARD_BREAKDOWN_CARD_TITLE_CLASS,
  DASHBOARD_SECTION_DESC_CLASS as DASHBOARD_BREAKDOWN_CARD_SUBTITLE_CLASS,
  DASHBOARD_EYEBROW_CLASS as DASHBOARD_BREAKDOWN_CARD_EYEBROW_CLASS,
  DASHBOARD_LOADING_CLASS as DASHBOARD_BREAKDOWN_CARD_LOADING_CLASS,
  DASHBOARD_LINK_CLASS as DASHBOARD_BREAKDOWN_CARD_LINK_CLASS,
};

export const DASHBOARD_BREAKDOWN_CARD_LIST_CLASS = "mt-4 space-y-3";

export const DASHBOARD_BREAKDOWN_CARD_ROW_LABEL_CLASS =
  "text-xs text-zinc-600 dark:text-zinc-400";

export const DASHBOARD_BREAKDOWN_CARD_ROW_VALUE_CLASS =
  "text-xs tabular-nums text-zinc-900 dark:text-zinc-100";

export const DASHBOARD_BREAKDOWN_CARD_BAR_TRACK_CLASS =
  "h-1.5 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800";

export const DASHBOARD_BREAKDOWN_CARD_BAR_FILL_CLASS = "h-1.5 rounded-full transition-all";
