import {
  LOGIN_FORM_BLURRED_CONTENT_CLASS,
  LOGIN_FORM_FIELD_GROUP_CLASS,
  LOGIN_FORM_FIELD_ICON_CLASS,
  LOGIN_FORM_FIELDS_CLASS,
  LOGIN_FORM_FOOTER_CLASS,
  LOGIN_FORM_FOOTER_LINK_CLASS,
  LOGIN_FORM_INPUT_CLASS,
  LOGIN_FORM_LOADING_CARD_CLASS,
  LOGIN_FORM_LOADING_OVERLAY_CLASS,
  LOGIN_FORM_MESSAGE_CLASS,
  LOGIN_FORM_PASSWORD_TOGGLE_CLASS,
  LOGIN_FORM_SHELL_CLASS,
  LOGIN_FORM_SUBMIT_CLASS,
  LOGIN_FORM_SUBMIT_INNER_CLASS,
  LOGIN_FORM_TITLE_CLASS,
} from "@/app/(marketing)/login/components/LoginForm/constants";

export {
  LOGIN_FORM_BLURRED_CONTENT_CLASS as SET_PASSWORD_FORM_BLURRED_CONTENT_CLASS,
  LOGIN_FORM_FIELD_GROUP_CLASS as SET_PASSWORD_FORM_FIELD_GROUP_CLASS,
  LOGIN_FORM_FIELD_ICON_CLASS as SET_PASSWORD_FORM_FIELD_ICON_CLASS,
  LOGIN_FORM_FIELDS_CLASS as SET_PASSWORD_FORM_FIELDS_CLASS,
  LOGIN_FORM_FOOTER_CLASS as SET_PASSWORD_FORM_FOOTER_CLASS,
  LOGIN_FORM_FOOTER_LINK_CLASS as SET_PASSWORD_FORM_FOOTER_LINK_CLASS,
  LOGIN_FORM_INPUT_CLASS as SET_PASSWORD_FORM_INPUT_CLASS,
  LOGIN_FORM_LOADING_CARD_CLASS as SET_PASSWORD_FORM_LOADING_CARD_CLASS,
  LOGIN_FORM_LOADING_OVERLAY_CLASS as SET_PASSWORD_FORM_LOADING_OVERLAY_CLASS,
  LOGIN_FORM_MESSAGE_CLASS as SET_PASSWORD_FORM_MESSAGE_CLASS,
  LOGIN_FORM_PASSWORD_TOGGLE_CLASS as SET_PASSWORD_FORM_PASSWORD_TOGGLE_CLASS,
  LOGIN_FORM_SHELL_CLASS as SET_PASSWORD_FORM_SHELL_CLASS,
  LOGIN_FORM_SUBMIT_CLASS as SET_PASSWORD_FORM_SUBMIT_CLASS,
  LOGIN_FORM_SUBMIT_INNER_CLASS as SET_PASSWORD_FORM_SUBMIT_INNER_CLASS,
  LOGIN_FORM_TITLE_CLASS as SET_PASSWORD_FORM_TITLE_CLASS,
};

export const SET_PASSWORD_FORM_LOADING_TITLE = "Updating password…";
export const SET_PASSWORD_FORM_TITLE_INVITE = "Set Password";
export const SET_PASSWORD_FORM_TITLE_RECOVERY = "Reset Password";
export const SET_PASSWORD_FORM_SUBMIT_INVITE = "Set Password";
export const SET_PASSWORD_FORM_SUBMIT_RECOVERY = "Update Password";
export const SET_PASSWORD_FORM_NEEDS_AUTH_MESSAGE =
  "This link is invalid or has expired. Request a new invite or reset link.";
export const SET_PASSWORD_MIN_LENGTH = 6;
