import {
  DASHBOARD_EYEBROW_CLASS,
  DASHBOARD_LINK_CLASS,
  DASHBOARD_SECTION_TITLE_CLASS,
  DASHBOARD_SIDE_PANEL_BODY_CLASS,
  DASHBOARD_SIDE_PANEL_CLASS,
} from "../../constants";

export {
  DASHBOARD_SIDE_PANEL_CLASS as DASHBOARD_TRIAGE_BREAKDOWN_PANEL_CLASS,
  DASHBOARD_SIDE_PANEL_BODY_CLASS as DASHBOARD_TRIAGE_BREAKDOWN_PANEL_BODY_CLASS,
  DASHBOARD_SECTION_TITLE_CLASS as DASHBOARD_TRIAGE_BREAKDOWN_TITLE_CLASS,
  DASHBOARD_EYEBROW_CLASS as DASHBOARD_TRIAGE_BREAKDOWN_EYEBROW_CLASS,
  DASHBOARD_LINK_CLASS as DASHBOARD_TRIAGE_BREAKDOWN_LINK_CLASS,
};

export const DASHBOARD_TRIAGE_BREAKDOWN_LIST_CLASS = "mt-4 flex min-h-0 flex-1 flex-col justify-center gap-3";

export const DASHBOARD_TRIAGE_BREAKDOWN_ROW_LABEL_CLASS =
  "text-xs text-zinc-600 dark:text-zinc-400";

export const DASHBOARD_TRIAGE_BREAKDOWN_ROW_VALUE_CLASS =
  "text-xs tabular-nums text-zinc-900 dark:text-zinc-100";

export const DASHBOARD_TRIAGE_BREAKDOWN_BAR_TRACK_CLASS =
  "h-1 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800";

export const DASHBOARD_TRIAGE_BREAKDOWN_BAR_FILL_CLASS = "h-1 rounded-full transition-all";

export const DASHBOARD_TRIAGE_BREAKDOWN_BAR_CRITICAL_CLASS = "bg-primary-orange/90";
export const DASHBOARD_TRIAGE_BREAKDOWN_BAR_WARNING_CLASS = "bg-amber-500/90";
export const DASHBOARD_TRIAGE_BREAKDOWN_BAR_INFO_CLASS = "bg-zinc-400/80 dark:bg-zinc-500";
