import {
  LOGIN_FORM_BLURRED_CONTENT_CLASS,
  LOGIN_FORM_FIELD_GROUP_CLASS,
  LOGIN_FORM_FIELD_ICON_CLASS,
  LOGIN_FORM_FIELDS_CLASS,
  LOGIN_FORM_FOOTER_CLASS,
  LOGIN_FORM_FOOTER_LINK_CLASS,
  LOGIN_FORM_INPUT_CLASS,
  LOGIN_FORM_LOADING_CARD_CLASS,
  LOGIN_FORM_LOADING_OVERLAY_CLASS,
  LOGIN_FORM_MESSAGE_CLASS,
  LOGIN_FORM_SHELL_CLASS,
  LOGIN_FORM_SUBMIT_CLASS,
  LOGIN_FORM_SUBMIT_INNER_CLASS,
  LOGIN_FORM_TITLE_CLASS,
} from "@/app/(marketing)/login/components/LoginForm/constants";

export {
  LOGIN_FORM_BLURRED_CONTENT_CLASS as FORGOT_PASSWORD_FORM_BLURRED_CONTENT_CLASS,
  LOGIN_FORM_FIELD_GROUP_CLASS as FORGOT_PASSWORD_FORM_FIELD_GROUP_CLASS,
  LOGIN_FORM_FIELD_ICON_CLASS as FORGOT_PASSWORD_FORM_FIELD_ICON_CLASS,
  LOGIN_FORM_FIELDS_CLASS as FORGOT_PASSWORD_FORM_FIELDS_CLASS,
  LOGIN_FORM_FOOTER_CLASS as FORGOT_PASSWORD_FORM_FOOTER_CLASS,
  LOGIN_FORM_FOOTER_LINK_CLASS as FORGOT_PASSWORD_FORM_FOOTER_LINK_CLASS,
  LOGIN_FORM_INPUT_CLASS as FORGOT_PASSWORD_FORM_INPUT_CLASS,
  LOGIN_FORM_LOADING_CARD_CLASS as FORGOT_PASSWORD_FORM_LOADING_CARD_CLASS,
  LOGIN_FORM_LOADING_OVERLAY_CLASS as FORGOT_PASSWORD_FORM_LOADING_OVERLAY_CLASS,
  LOGIN_FORM_MESSAGE_CLASS as FORGOT_PASSWORD_FORM_MESSAGE_CLASS,
  LOGIN_FORM_SHELL_CLASS as FORGOT_PASSWORD_FORM_SHELL_CLASS,
  LOGIN_FORM_SUBMIT_CLASS as FORGOT_PASSWORD_FORM_SUBMIT_CLASS,
  LOGIN_FORM_SUBMIT_INNER_CLASS as FORGOT_PASSWORD_FORM_SUBMIT_INNER_CLASS,
  LOGIN_FORM_TITLE_CLASS as FORGOT_PASSWORD_FORM_TITLE_CLASS,
};

export const FORGOT_PASSWORD_FORM_TITLE = "Forgot Password";
export const FORGOT_PASSWORD_FORM_SUBMIT_LABEL = "Send Reset Link";
export const FORGOT_PASSWORD_FORM_LOADING_TITLE = "Sending reset link…";
export const FORGOT_PASSWORD_FORM_SUCCESS_MESSAGE =
  "If an account exists for that email, we sent a password reset link.";
