import {
  DASHBOARD_DIVIDE_CLASS,
  DASHBOARD_EMPTY_CLASS,
  DASHBOARD_LOADING_CLASS,
  DASHBOARD_PANEL_BODY_CLASS,
  DASHBOARD_PANEL_CLASS,
  DASHBOARD_STAT_LABEL_CLASS,
  DASHBOARD_STAT_META_CLASS,
  DASHBOARD_STAT_VALUE_CLASS,
  dashboardStatValueToneClass,
} from "../../constants";

export {
  DASHBOARD_PANEL_BODY_CLASS,
  DASHBOARD_STAT_LABEL_CLASS as DASHBOARD_KPI_LABEL_CLASS,
  DASHBOARD_STAT_META_CLASS as DASHBOARD_KPI_SUB_CLASS,
  DASHBOARD_STAT_VALUE_CLASS as DASHBOARD_KPI_VALUE_CLASS,
  DASHBOARD_EMPTY_CLASS,
  DASHBOARD_LOADING_CLASS as DASHBOARD_KPI_LOADING_CLASS,
  dashboardStatValueToneClass as dashboardKpiValueToneClass,
};

export const DASHBOARD_KPI_PANEL_CLASS = DASHBOARD_PANEL_CLASS;

export const DASHBOARD_KPI_GRID_CLASS = `grid sm:grid-cols-2 lg:grid-cols-4 divide-y sm:divide-y-0 sm:divide-x ${DASHBOARD_DIVIDE_CLASS}`;

export const DASHBOARD_KPI_CELL_CLASS = "px-6 py-5 sm:px-5 lg:px-6";
